jobs:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      before_script:
        - cd web-api
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet test -c Release

    - language: node_js
      node_js: 13
      before_script:
        - cd web-admin
      script:
        - npm install
        - npm run build
        # - npm test

    - language: node_js
      node_js: 13
      before_script:
        - cd web-client
      script:
        - npm install --silent
        - npm run build
        # - npm test

    - services:
        - docker
      script:
        - docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
