stages:
  - test
  - name: deploy
    if: branch = master
  - name: local docker
    if: branch = dev

jobs:
  include:
    - stage: test
      name: 'Web API tests'
      language: csharp
      mono: none
      dotnet: 3.1
      before_script:
        - cd web-api
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet test -c Release

    - stage: test
      name: 'Web Admin tests'
      language: node_js
      node_js: 13
      before_script:
        - cd web-admin
      script:
        - npm install
        - npm run build
        - npm test

    - stage: test
      name: 'Web Client tests'
      language: node_js
      node_js: 13
      before_script:
        - cd web-client
      script:
        - npm install --silent
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

    - stage: deploy
      name: 'Deploy Web Sites to Firebase hosting'
      language: node_js
      node_js: 13
      script: ./deploy/build-sites.sh
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: 'ftbkjPojl80yH+Fj37L/bJkTFkFMHnzj9f1j9pmvG3w6QGPxcWwXQP8QsxRu7pSH8biMqH/GUtE+Qff6HtgETYtl8mrYgUMOKz0ABFuKZDTx3y2e7kLATxAnRgOGPYD2tWbqaZV1xf0+uaG+XeZwg9Q+22R/9PIceXGOLUtqqgAXzkz9hqFUFeD4hgLuLy7ybdX715qBnMNt8NTbYQCZ6j1TKlQMpbsMhQyz48byhV2cEqQDzVDCKaRZwOHneFvZvM476NYU+QVw7gvROsmB7dV2iO4m5gLfsjd3caHTI0PZFJALvw0LNhah7i7SIYneTz/fvntH4WdSdEQOUjVwUHwwbMiZKf1ksUAOSKSYpWbT8hl9GjqyJrYmgNnotV8n6HlVi/G2Nuoa10Y8M82wZEG2AyWZf+0MG1GT3Iv6KsIPAVcquoPY0ETSe6gwoXUHfi8lTiWoJ41wGOXlDwdYTJFMZkqt2J2gfFMHtjQHag4R0k6/ToOXwLAJzfK4nnU5fM/GudV9Q3mLcUuHNiFp5xgN0dK0leHVA9ommLcpImfvkcGSCFoepBBddl1KscXSXUWDwhrR7hxHa3yPcIsYTPvNTT+bLj6Tt8xIeCU56YSU0v5Ehbucwaf3eKCFkJXnvjccQa7At3NQKGAMKN7ipWbWWYVOTX/BuglRp5m7ryA='
        message: 'Travis-CI automated deployment'

    - stage: local docker
      name: 'Local environment deployment test'
      services:
        - docker
      script:
        - docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
