jobs:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      before_script:
        - cd web-api
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet test -c Release

    - language: node_js
      node_js: 12
      before_script:
        - cd web-admin
      script:
        - npm install
        - npm run build
        - npm test
