version: '3.4'

services:
  webapi:
    build:
      context: web-api
      dockerfile: docker/Dockerfile

  webclient:
    build:
      context: web-client
      dockerfile: docker/Dockerfile
    depends_on:
      - webapi
