version: '3.4'

services:
  webapi:
    build:
      dockerfile: docker/Dockerfile.dev
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  webclient:
    ports:
      - '8080:8080'

  webadmin:
    ports:
      - '8081:80'
