version: '3.4'

services:
  webapi:
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Oidc__Audience=coffeedose-eaef2
      - Oidc__Authority=https://securetoken.google.com/coffeedose-eaef2
      - Oidc__Issuer=https://securetoken.google.com/coffeedose-eaef2

  webclient:
    ports:
      - '8080:8080'

  webadmin:
    ports:
      - '8081:80'
